Tehas/Areas/Cabinet/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Klinik.Frontend.Areas.Cabinet.Models;
using Klinik.Frontend.Helpers;
using Klinik.Utils.BusinessOperations.Doctors;
using Klinik.Utils.DataBase.Security;

namespace Klinik.Frontend.Areas.Cabinet.Controllers
{
    public class DoctorController : Controller
    {
        // GET: Cabinet/Menu/List
        public ActionResult List()
        {
            if (!SessionHelpers.IsAuthentificated())
                return RedirectToAction("Login", "Authorize");

            var operation2 = new LoadAllDoctorsOperation();
            operation2.ExcecuteTransaction();
            return View(operation2._doctors);
        }
        
        // GET: Cabinet/menu/List
        public ActionResult Detail(int id)
        {
            if (!SessionHelpers.IsAuthentificated())
                return RedirectToAction("Login", "Authorize");

            if (id < 1)
                return HttpNotFound();
            
            var operation2 = new LoadDoctorOperation(id);
            operation2.ExcecuteTransaction();
            if(operation2._doctor == null)
                return HttpNotFound();

            return View(operation2._doctor);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Detail(Doctor model, HttpPostedFileBase image)
        {
            if (!SessionHelpers.IsAuthentificated())
                return RedirectToAction("Login", "Authorize");
            var op = new UpdateDoctorOperation(model, image);
            op.ExcecuteTransaction();
            if (op._doctor == null)
                return HttpNotFound();

            return View(op._doctor);
        }

        [HttpPost]
        public ActionResult Delete(int[] ids)
        {
            if (!SessionHelpers.IsAuthentificated())
                return RedirectToAction("Login", "Authorize");
            DeleteDoctorsOperation op = new DeleteDoctorsOperation(ids);
            op.ExcecuteTransaction();
            
            var operation = new LoadAllDoctorsOperation();
            operation.ExcecuteTransaction();

            return PartialView("Partial/_listOfDoctorsPartial", operation._doctors);
        }

        public ActionResult Add()
        {
            if (!SessionHelpers.IsAuthentificated())
                return RedirectToAction("Login", "Authorize");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Doctor model, HttpPostedFileBase image)
        {
            if (!SessionHelpers.IsAuthentificated())
                return RedirectToAction("Login", "Authorize");

            AddDoctorOperation op = new AddDoctorOperation(model, image);
            op.ExcecuteTransaction();

            return RedirectToAction("List");
        }
    }
}

Tehas/Areas/Cabinet/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Klinik.Frontend.Areas.Cabinet.Models;
using Klinik.Frontend.Helpers;
using Klinik.Utils.BusinessOperations.Products;
using Klinik.Utils.DataBase.Products;

namespace Klinik.Frontend.Areas.Cabinet.Controllers
{
    public class ServiceController : Controller
    {
        // GET: Cabinet/Menu/List
        public ActionResult List()
        {
            if (!SessionHelpers.IsAuthentificated())
                return RedirectToAction("Login", "Authorize");

            var operation2 = new LoadAllProductsOperation();
            operation2.ExcecuteTransaction();
            return View(operation2._products);
        }
        
        // GET: Cabinet/menu/List
        public ActionResult Detail(int id)
        {
            if (!SessionHelpers.IsAuthentificated())
                return RedirectToAction("Login", "Authorize");

            if (id < 1)
                return HttpNotFound();
            
            var operation2 = new LoadProductOperation(id);
            operation2.ExcecuteTransaction();
            if(operation2._product == null)
                return HttpNotFound();

            return View(operation2._product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Detail(Product model, HttpPostedFileBase image)
        {
            if (!SessionHelpers.IsAuthentificated())
                return RedirectToAction("Login", "Authorize");
            UpdateProductOperation op = new UpdateProductOperation(model, image);
            op.ExcecuteTransaction();
            if (op._product == null)
                return HttpNotFound();

            return View(op._product);
        }

        [HttpPost]
        public ActionResult Delete(int[] ids)
        {
            if (!SessionHelpers.IsAuthentificated())
                return RedirectToAction("Login", "Authorize");
            DeleteProductsOperation op = new DeleteProductsOperation(ids);
            op.ExcecuteTransaction();
            
            var operation = new LoadAllProductsOperation();
            operation.ExcecuteTransaction();

            return PartialView("Partial/_listOfProductsPartial", operation._products);
        }

        public ActionResult Add()
        {
            if (!SessionHelpers.IsAuthentificated())
                return RedirectToAction("Login", "Authorize");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Product model, HttpPostedFileBase image)
        {
            if (!SessionHelpers.IsAuthentificated())
                return RedirectToAction("Login", "Authorize");

            AddProductOperation op = new AddProductOperation(model, image);
            op.ExcecuteTransaction();

            return RedirectToAction("List");
        }
    }
}

Tehas/Controllers/KlinikController.cs
using System.Linq;
using System.Collections.Generic;
using System.Web.Mvc;
using Klinik.Frontend.Models;
using Klinik.Utils.DataBase.Emails;
using Klinik.Utils.BusinessOperations.Comments;
using Klinik.Utils.BusinessOperations.Orders;
using Klinik.Utils.BusinessOperations.Doctors;
using Klinik.Utils.BusinessOperations.Products;

namespace Klinik.Frontend.Controllers
{
    public class KlinikController : Controller
    {
        private static Dictionary<string, int> ServiceIds { get; set; }

        public ActionResult Index()
        {
            var op = new LoadAllDoctorsOperation();
            op.ExcecuteTransaction();
            ViewBag.Doctors = op._doctors;
            var op2 = new LoadAllProductsOperation();
            op2.ExcecuteTransaction();
            ViewBag.Products = op2._products;
            var op3 = new LoadCommentsOperation(1, 4);
            op3.ExcecuteTransaction();
            ViewBag.Comments = op3._comments;
            ViewBag.NavMenuEnabled = true;
            return View(/*op._pageDescription*/);
        }
        public ActionResult Doctor(int id)
        {
            var op = new LoadDoctorOperation(id);
            op.ExcecuteTransaction();
            ViewBag.NavMenuEnabled = false;
            return View(op._doctor);
        }

        [Route("[controller]/[action]/{id}")]
        public ActionResult Service(int id)
        {
            if (id <= 0)
                return HttpNotFound();

            var op = new LoadAllProductsOperation();
            op.ExcecuteTransaction();
            ViewBag.NavMenuEnabled = false;
            var service = op._products.FirstOrDefault(x => x.Id == id);
            if (service == null)
                return HttpNotFound();

            return RedirectToRoute(service.Tag);
        }

        [Route("{serviceName}")]
        public ActionResult ServiceName(string serviceName)
        {
            if (string.IsNullOrEmpty(serviceName))
                return HttpNotFound();

            var op = new LoadAllProductsOperation();
            op.ExcecuteTransaction();
            ViewBag.NavMenuEnabled = false;
            var service = op._products.FirstOrDefault(x => x.Tag == serviceName.ToLower());
            if (service == null)
                return HttpNotFound();

            ViewBag.Selected = service;
            return View("Service", op._products);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public JsonResult SendMessage(EmailModel mail)
        {
            var operation = new SendMailOperation(mail.Name, mail.Phone, mail.Email);
            operation.ExcecuteTransaction();
            return Json("Отправлено");
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult SendFeedback(Comment model)
        {
            var op = new AddCommentOperation(model);
            op.ExcecuteTransaction();
            return Json("Отправлено");
        }
    }
}

Tehas/Views/Klinik/Add.cshtml
@using Tehas.Utils.DataBase.PagesDesc;
@model PageDescription

@using (@Html.BeginForm("Add", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.TextBoxFor(m => m.ActionName);
    @Html.TextBoxFor(m => m.ControllerName);
    @Html.TextBoxFor(m => m.Description);
    @Html.TextBoxFor(m => m.Title);
    @Html.TextBoxFor(m => m.VideoURL);
    <input type="file" multiple="multiple" accept="image/*" name="images" />
    <input type="submit" value="OK"/>
}

Tehas/Views/Klinik/_feedback.cshtml
@model Klinik.Utils.DataBase.Emails.Comment

@using (Ajax.BeginForm("SendFeedback", "Klinik", null, new AjaxOptions
{
    //UpdateTargetId = "send_feedback",
    OnSuccess = "SendFeedbackOnComplete"
}, new { @id = "feedback-form" }))

{

    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.TextBoxFor(x => x.Username, new { @placeholder = "Имя" })
    @Html.TextBoxFor(x => x.Company, new { @placeholder = "Компания и должность" })
    <p>
        @Html.TextAreaFor(x => x.Message, new { @placeholder = "Отзыв" })
    </p>
        <button class="applicationButton" type="submit" form="feedback-form">Отправить</button>
}

Tehas/Views/Klinik/_message-modal.cshtml
@model Klinik.Frontend.Models.EmailModel

@using (Ajax.BeginForm("SendMessage", "Klinik", null, new AjaxOptions
{
    //UpdateTargetId = "send_message-modal",
    OnSuccess = "SendMessageOnCompleteModal"
}, new { @id = "message-form-modal" }))

{

    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="formflex_contact">
        <h4>Ваши контактные данные:</h4>
        @Html.TextBoxFor(x => x.Name, new { @placeholder = "Имя" })
        @Html.TextBoxFor(x => x.Email, new { @placeholder = "Email" })
        @Html.TextBoxFor(x => x.Phone, new { @placeholder = "Телефон" })
    </div>
    <button class="applicationButton" type="submit" form="message-form-modal">Отправить</button>
}

Tehas/Views/Klinik/_message.cshtml
@model Klinik.Frontend.Models.EmailModel

@using (Ajax.BeginForm("SendMessage", "Klinik", null, new AjaxOptions
{
    //UpdateTargetId = "send_message",
    OnSuccess = "SendMessageOnComplete"
}, new { @id = "message-form" }))

{

    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.TextBoxFor(x => x.Name, new { @placeholder = "Имя" })
    @Html.TextBoxFor(x => x.Email, new { @placeholder = "Email" })
    @Html.TextBoxFor(x => x.Phone, new { @placeholder = "Телефон" })

    <button class="applicationButton" type="submit" form="message-form">Отправить</button>
}

Tehas/Views/Klinik/doctor.cshtml
@using Klinik.Utils.DataBase.Security
@model Doctor
<div class="doctor">
    <div class="doctor_card">
        <a href="#"><img src="@Url.Content(Model.Image.Url + Model.Image.FileName)" alt="" /></a>
        <div class="info">
            <h4><a href="#">@Model.ShortName</a></h4>
            <h5>@Model.Position</h5>
            <p>@Model.Slogan</p>
        </div>
    </div>
    <div class="text">
        <p>@Html.Raw(Model.Description)</p>
    </div>
</div>

Tehas/Views/Klinik/service.cshtml
@using Klinik.Utils.DataBase.Products
@model List<Product>
@{
    Product selected = ViewBag.Selected;
}
@section Scripts {
    <script>
        function setProd(imgUrl, title, desc) {
            $('.picture img').attr('src', imgUrl);
            $('.picture .h3 h3').text(title);
            $('.text1 p').html(desc);

            var html = title.substring(0, title.length / 2) + '<span class="blue">' + title.substring(title.length / 2, title.length) + '</span>';
            $('.h22 h3#title').html(html);
        };
    </script>
}
<div class="h22"><h1 id="title">@selected.Title.Substring(0, selected.Title.Length / 2)<span class="blue">@selected.Title.Substring(selected.Title.Length / 2, selected.Title.Length - (selected.Title.Length / 2))</span></h1></div>

<div class="doctor">

    <div class="wrapper_service">
        <div class="service">
            @if (selected != null)
            {
                <div class="picture">
                    @if (selected.Image != null)
                    {
                        <img src="@Url.Content(selected.Image.Url + selected.Image.FileName)" alt="" />
                    }
                    <div class="h3"><h1>@selected.Title</h1></div>
                </div>
            }
            <p>@Html.Raw(selected.Description)</p>

        </div>
    </div>

    <div class="text1">
        <div class="info">
            <div class="links">
                @foreach (var pr in Model)
                {
                    if (pr.Id != selected.Id)
                    {
                        <a href="/@pr.Tag">@pr.Title</a>
                    }
                    @*<a href="#" onclick="setProd('@(pr.Image!= null? Url.Content(pr.Image.Url + pr.Image.FileName) : "")','@pr.Title', '@(pr.Description?.Replace(Environment.NewLine, " "))')">@pr.Title</a>*@
                }
            </div>
        </div>
    </div>
</div>